workflows:
  kivy-ios-unsigned:
    name: Beluga Chat
    environment:
      xcode: latest
      vars:
        APP_NAME: "beluga_chat_sapp"
        BUNDLE_ID: "com.beluga.chatt"

    scripts:
      - name: Cài toàn bộ công cụ build cần thiết
        script: |
          brew update
          brew install python@3.9 autoconf automake libtool pkg-config gettext gawk bash git
          brew link --overwrite automake autoconf libtool gettext
          
          echo "✅ Kiểm tra tool:"
          which automake && automake --version
          which autoconf && autoconf --version
          which libtool && libtool --version
          which pkg-config && pkg-config --version

      - name: Cài kivy-ios và dependencies
        script: |
          python3 -m pip install --upgrade pip
          pip3 install wheel virtualenv Cython
          pip3 install kivy-ios==2022.07.19
          
          # Sửa lỗi kivy-ios
          TOOLCHAIN_DIR=$(pip3 show kivy-ios | grep Location | cut -d ' ' -f 2)
          echo "Kivy-iOS path: $TOOLCHAIN_DIR"
          
          # Sửa file kivy-ios/toolchain.py nếu gặp lỗi libffi
          cd $TOOLCHAIN_DIR/kivy_ios
          cat > patch_libffi.py << 'EOL'
import os
import fileinput

# Patch file libffi.py để sửa lỗi cấu hình
recipe_file = 'recipes/libffi/__init__.py'
if os.path.exists(recipe_file):
    print("Patching libffi recipe...")
    with fileinput.FileInput(recipe_file, inplace=True) as file:
        for line in file:
            if 'def get_host(self, arch):' in line:
                print(line, end='')
                print('        if "arm64" in arch:')
                print('            return "aarch64-apple-darwin"')
            else:
                print(line, end='')
    print("Done patching libffi recipe")
else:
    print("libffi recipe file not found")
EOL
          python3 patch_libffi.py

      - name: Chuẩn bị thư mục build
        script: |
          mkdir -p $CM_BUILD_DIR/iosbuild
          cd $CM_BUILD_DIR/iosbuild

      - name: Build dependencies riêng cho libffi
        script: |
          cd $CM_BUILD_DIR/iosbuild
          echo "📦 Building libffi với cấu hình đặc biệt..."
          export MAKEFLAGS="-j2"
          
          # Triển khai 2 giải pháp có thể sửa lỗi libffi
          
          # Giải pháp 1: Dùng phiên bản cụ thể và tham số đặc biệt
          toolchain build libffi || {
            echo "⚠️ Thử lại với tham số cụ thể..."
            # Xóa bản cài đặt cũ nếu có
            rm -rf ~/.kivy-ios/build/libffi
            rm -rf ~/.kivy-ios/dist/libffi
            
            # Thử với tham số cache_env=False
            toolchain build libffi --cache-env=False || {
              echo "⚠️ Vẫn thất bại, thử phương án cuối..."
              # Sửa lỗi libffi theo cách thủ công
              KIVY_IOS_ROOT=$(pip3 show kivy-ios | grep Location | cut -d ' ' -f 2)/kivy_ios
              cd $KIVY_IOS_ROOT
              echo "Kivy-iOS root: $KIVY_IOS_ROOT"
              python3 toolchain.py build libffi --cache-env=False || {
                echo "❌ Không thể build libffi, bỏ qua và thử build các dependencies khác..."
              }
            }
          }

      - name: Build các dependencies còn lại
        script: |
          cd $CM_BUILD_DIR/iosbuild
          export MAKEFLAGS="-j2"
          export KIVY_IOS_JOBS=2
          
          # Thử build từng gói riêng lẻ
          for lib in openssl python3 kivy; do
            echo "📦 Building $lib..."
            toolchain build $lib || { 
              echo "⚠️ Thất bại lần đầu với $lib, thử lại với cache_env=False..."
              toolchain build $lib --cache-env=False || {
                echo "❌ Build $lib không thành công, bỏ qua..."
              }
            }
          done
          
          # Kiểm tra xem đã build đủ dependencies chưa
          if [ ! -d ~/.kivy-ios/dist/python3 ] || [ ! -d ~/.kivy-ios/dist/kivy ]; then
            echo "❌ Thiếu dependencies quan trọng, không thể tiếp tục"
            exit 1
          fi

      - name: Tạo project từ source
        script: |
          cd $CM_BUILD_DIR/iosbuild
          
          # Kiểm tra file main.py
          if [ -f "../kivy_chat_app/main.py" ]; then
            echo "✅ Using main.py from kivy_chat_app"
            toolchain create $APP_NAME ../kivy_chat_app/main.py
          elif [ -f "../main.py" ]; then
            echo "✅ Using main.py from root"
            toolchain create $APP_NAME ../main.py
          else
            echo "❌ main.py not found"
            find .. -name "main.py"
            exit 1
          fi
          
          # Build app
          echo "⏳ Building app..."
          toolchain build $APP_NAME || {
            echo "⚠️ Thất bại với build app, thử lại..."
            toolchain build $APP_NAME --no-clean
          }

      - name: Chuẩn bị Xcode project
        script: |
          cd $CM_BUILD_DIR/iosbuild
          toolchain xcode $APP_NAME
          cd $APP_NAME-ios
          
          PLIST_PATH="$APP_NAME/Info.plist"
          if [ -f "$PLIST_PATH" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" "$PLIST_PATH"
            echo "✅ Updated Bundle ID"
          else
            echo "⚠️ Info.plist not found at $PLIST_PATH"
            find . -name "Info.plist"
            exit 1
          fi

      - name: Build IPA
        script: |
          cd $CM_BUILD_DIR/iosbuild/$APP_NAME-ios
          
          cat > exportOptions.plist <<EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>manual</string>
          </dict>
          </plist>
          EOL
          
          # Build và archive không ký
          xcodebuild -scheme $APP_NAME -configuration Release \
                    -archivePath $APP_NAME.xcarchive archive \
                    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
                    
          # Export IPA
          xcodebuild -exportArchive -archivePath $APP_NAME.xcarchive \
                    -exportOptionsPlist exportOptions.plist \
                    -exportPath build/Release-iphoneos \
                    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          
          echo "✅ Build completed. IPA location:"
          find build -name "*.ipa"

    artifacts:
      - iosbuild/$APP_NAME-ios/build/Release-iphoneos/*.ipa 
