workflows:
  kivy-ios-unsigned:
    name: Beluga Chat
    environment:
      xcode: latest
      vars:
        APP_NAME: "beluga_chat_sapp"
        BUNDLE_ID: "com.beluga.chatt"
    scripts:
      - name: Cài Python, pip & automake
        script: |
          brew install python
          brew install automake
          pip3 install --upgrade pip
          pip3 install virtualenv
      - name: Cài kivy-ios
        script: |
          pip3 install kivy-ios
      - name: Build dependencies
        script: |
          cd $CM_BUILD_DIR
          mkdir iosbuild
          cd iosbuild
          # Lệnh create - QUAN TRỌNG: loại bỏ $BUNDLE_ID ở cuối
          toolchain create $APP_NAME ../kivy_chat_app/main.py
          # Loại bỏ pycryptodome khỏi danh sách build
          toolchain build python3 kivy requests pillow
          toolchain build $APP_NAME
      - name: Tạo Xcode project và sửa Bundle ID
        script: |
          cd $CM_BUILD_DIR/iosbuild
          toolchain xcode $APP_NAME
          # Sửa bundle ID trong Info.plist
          cd $CM_BUILD_DIR/iosbuild/$APP_NAME-ios
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" "$APP_NAME/Info.plist"
      - name: Build IPA unsigned
        script: |
          cd $CM_BUILD_DIR/iosbuild/$APP_NAME-ios
          xcodebuild -scheme $APP_NAME -configuration Release -archivePath $APP_NAME.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive -archivePath $APP_NAME.xcarchive -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?><plist version="1.0"><dict><key>method</key><string>development</string><key>signingStyle</key><string>manual</string></dict></plist>') -exportPath build/Release-iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - iosbuild/$APP_NAME-ios/build/Release-iphoneos/*.ipa
