workflows:
  kivy-ios-unsigned:
    name: Beluga Chat
    environment:
      xcode: latest
      vars:
        APP_NAME: "beluga_chat_sapp"
        BUNDLE_ID: "com.beluga.chatt"

    scripts:
      - name: Cài toàn bộ công cụ build cần thiết
        script: |
          brew update
          brew install python@3.9 autoconf automake libtool pkg-config gettext gawk bash git
          brew link --overwrite automake autoconf libtool gettext
          
          echo "✅ Kiểm tra tool:"
          which automake && automake --version
          which autoconf && autoconf --version
          which libtool && libtool --version
          which pkg-config && pkg-config --version

      - name: Cài kivy-ios và dependencies
        script: |
          python3 -m pip install --upgrade pip
          pip3 install wheel virtualenv Cython
          pip3 install kivy-ios==2022.07.19
          
          # Sửa lỗi kivy-ios
          TOOLCHAIN_DIR=$(pip3 show kivy-ios | grep Location | cut -d ' ' -f 2)
          echo "Kivy-iOS path: $TOOLCHAIN_DIR"
          
          # Sửa file kivy-ios/toolchain.py nếu gặp lỗi libffi
          cd $TOOLCHAIN_DIR/kivy_ios
          cat > patch_libffi.py << 'EOF'
          import os
          import fileinput

          # Patch file libffi.py để sửa lỗi cấu hình
          recipe_file = 'recipes/libffi/__init__.py'
          if os.path.exists(recipe_file):
              print("Patching libffi recipe...")
              with fileinput.FileInput(recipe_file, inplace=True) as file:
                  for line in file:
                      if 'def get_host(self, arch):' in line:
                          print(line, end='')
                          print('        if "arm64" in arch:')
                          print('            return "aarch64-apple-darwin"')
                      else:
                          print(line, end='')
              print("Done patching libffi recipe")
          else:
              print("libffi recipe file not found")
          EOF
          python3 patch_libffi.py
          
          # Xóa cache cũ nếu có để clean build
          rm -rf ~/.kivy-ios/build/* || true
          rm -rf ~/.kivy-ios/dist/* || true

      - name: Chuẩn bị thư mục build
        script: |
          mkdir -p $CM_BUILD_DIR/iosbuild
          cd $CM_BUILD_DIR/iosbuild

      - name: Build iOS dependencies
        script: |
          cd $CM_BUILD_DIR/iosbuild
          export MAKEFLAGS="-j2"
          export KIVY_IOS_JOBS=2
          
          # Build các dependencies chính xác theo thứ tự
          echo "📦 Building libffi..."
          toolchain build libffi || {
            echo "⚠️ Thử lại libffi sau khi xóa cache..."
            rm -rf ~/.kivy-ios/build/libffi
            rm -rf ~/.kivy-ios/dist/libffi
            toolchain build libffi || echo "⚠️ Thất bại với libffi, tiếp tục xử lý..."
          }
          
          echo "📦 Building openssl..."
          toolchain build openssl || {
            echo "⚠️ Thử lại openssl sau khi xóa cache..."
            rm -rf ~/.kivy-ios/build/openssl
            rm -rf ~/.kivy-ios/dist/openssl
            toolchain build openssl || echo "⚠️ Thất bại với openssl, tiếp tục xử lý..."
          }
          
          echo "📦 Building python3..."
          toolchain build python3 || {
            echo "⚠️ Thử lại python3 sau khi xóa cache..."
            rm -rf ~/.kivy-ios/build/python3
            rm -rf ~/.kivy-ios/dist/python3
            toolchain build python3 || {
              echo "❌ Lỗi Python3 - Đây là thành phần quan trọng"
              exit 1
            }
          }
          
          echo "📦 Building kivy..."
          toolchain build kivy || {
            echo "⚠️ Thử lại kivy sau khi xóa cache..."
            rm -rf ~/.kivy-ios/build/kivy
            rm -rf ~/.kivy-ios/dist/kivy
            toolchain build kivy || {
              echo "❌ Lỗi Kivy - Đây là thành phần quan trọng"
              exit 1
            }
          }
          
          # Kiểm tra xem đã build đủ dependencies chưa
          if [ ! -d ~/.kivy-ios/dist/python3 ]; then
            echo "❌ Thiếu Python3, không thể tiếp tục"
            exit 1
          fi
          
          if [ ! -d ~/.kivy-ios/dist/kivy ]; then
            echo "❌ Thiếu Kivy, không thể tiếp tục"
            exit 1
          fi
          
          echo "✅ Đã build xong dependencies chính"

      - name: Tạo project từ source
        script: |
          cd $CM_BUILD_DIR/iosbuild
          
          # Kiểm tra file main.py
          if [ -f "../kivy_chat_app/main.py" ]; then
            echo "✅ Using main.py from kivy_chat_app"
            toolchain create $APP_NAME ../kivy_chat_app/main.py
          elif [ -f "../main.py" ]; then
            echo "✅ Using main.py from root"
            toolchain create $APP_NAME ../main.py
          else
            echo "❌ main.py not found"
            find .. -name "main.py"
            exit 1
          fi
          
          # Build app
          echo "⏳ Building app..."
          toolchain build $APP_NAME || {
            echo "⚠️ Thất bại với build app, thử lại không clean..."
            toolchain build $APP_NAME
          }

      - name: Chuẩn bị Xcode project
        script: |
          cd $CM_BUILD_DIR/iosbuild
          toolchain xcode $APP_NAME
          cd $APP_NAME-ios
          
          PLIST_PATH="$APP_NAME/Info.plist"
          if [ -f "$PLIST_PATH" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" "$PLIST_PATH"
            echo "✅ Updated Bundle ID"
          else
            echo "⚠️ Info.plist not found at $PLIST_PATH"
            find . -name "Info.plist"
            exit 1
          fi

      - name: Build IPA
        script: |
          cd $CM_BUILD_DIR/iosbuild/$APP_NAME-ios
          
          cat > exportOptions.plist <<EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>manual</string>
          </dict>
          </plist>
          EOL
          
          # Build và archive không ký
          xcodebuild -scheme $APP_NAME -configuration Release \
                    -archivePath $APP_NAME.xcarchive archive \
                    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
                    
          # Export IPA
          xcodebuild -exportArchive -archivePath $APP_NAME.xcarchive \
                    -exportOptionsPlist exportOptions.plist \
                    -exportPath build/Release-iphoneos \
                    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          
          echo "✅ Build completed. IPA location:"
          find build -name "*.ipa"

    artifacts:
      - iosbuild/$APP_NAME-ios/build/Release-iphoneos/*.ipa 
