workflows:
  kivy-ios-unsigned:
    name: Beluga Chat
    environment:
      xcode: latest
      vars:
        APP_NAME: "beluga_chat_sapp"
        BUNDLE_ID: "com.beluga.chatt"

    scripts:
      - name: Cài toàn bộ công cụ build cần thiết (FULL FIX)
        script: |
          brew update

          # Cài đầy đủ các tool cần thiết cho python3, libffi, openssl, v.v.
          brew install python \
                       autoconf automake libtool pkg-config \
                       gettext gawk bash git

          # Đảm bảo chúng được link đúng
          brew link --overwrite automake
          brew link --overwrite libtool
          brew link --overwrite autoconf
          brew link --overwrite gettext

          # Kiểm tra lại PATH và tool đã sẵn sàng
          echo "✅ Kiểm tra tool:"
          which automake && automake --version
          which autoconf && autoconf --version
          which libtool  && libtool --version
          which pkg-config && pkg-config --version

      - name: Cài kivy-ios
        script: |
          pip3 install --upgrade pip
          pip3 install virtualenv
          pip3 install kivy-ios

      - name: Tạo thư mục build
        script: |
          mkdir -p $CM_BUILD_DIR/iosbuild
          cd $CM_BUILD_DIR/iosbuild

      - name: Build các dependencies (python3, kivy)
        script: |
          cd $CM_BUILD_DIR/iosbuild

          # Hạn chế RAM sử dụng để tránh OOM
          export MAKEFLAGS="-j2"
          export KIVY_IOS_JOBS=2

          echo "📦 Build libffi..."
          toolchain build libffi || { echo "❌ Build libffi failed"; exit 1; }

          echo "📦 Build python3..."
          toolchain build python3 || { echo "❌ Build python3 failed"; exit 1; }

          echo "📦 Build kivy..."
          toolchain build kivy || { echo "❌ Build kivy failed"; exit 1; }

      - name: Tạo project từ main.py
        script: |
          cd $CM_BUILD_DIR/iosbuild

          echo "📁 Kiểm tra workspace:"
          ls -la ../

          if [ -f "../kivy_chat_app/main.py" ]; then
            echo "✅ Found main.py trong kivy_chat_app"
            toolchain create $APP_NAME ../kivy_chat_app/main.py
          elif [ -f "../main.py" ]; then
            echo "✅ Found main.py trong thư mục gốc"
            toolchain create $APP_NAME ../main.py
          else
            echo "❌ Không tìm thấy main.py"
            exit 1
          fi

          toolchain build $APP_NAME

      - name: Tạo Xcode project & sửa Bundle ID
        script: |
          cd $CM_BUILD_DIR/iosbuild
          toolchain xcode $APP_NAME
          cd $APP_NAME-ios

          echo "📁 Kiểm tra cấu trúc thư mục:"
          ls -la
          echo "📁 Bên trong thư mục app:"
          ls -la $APP_NAME/

          PLIST_PATH="$APP_NAME/Info.plist"
          if [ -f "$PLIST_PATH" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" "$PLIST_PATH"
            echo "✅ Đã sửa Bundle ID trong Info.plist"
          else
            echo "⚠️ Không tìm thấy Info.plist"
            find . -name "Info.plist"
          fi

      - name: Build IPA unsigned
        script: |
          cd $CM_BUILD_DIR/iosbuild/$APP_NAME-ios

          echo "📦 Build archive..."
          xcodebuild -scheme $APP_NAME -configuration Release -archivePath $APP_NAME.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

          echo "📦 Tạo exportOptions.plist"
          cat > exportOptions.plist << EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>manual</string>
          </dict>
          </plist>
          EOL

          echo "📦 Export IPA"
          xcodebuild -exportArchive -archivePath $APP_NAME.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/Release-iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

          echo "📦 Kiểm tra IPA:"
          find build -name "*.ipa"

    artifacts:
      - iosbuild/$APP_NAME-ios/build/Release-iphoneos/*.ipa
