workflows:
  kivy-ios-unsigned:
    name: Beluga Chat
    environment:
      xcode: latest
      vars:
        APP_NAME: "beluga_chat_sapp"
        BUNDLE_ID: "com.beluga.chatt"
    scripts:
      - name: Cài Python & công cụ build
        script: |
          brew install python automake libtool pkg-config
          pip3 install --upgrade pip
          pip3 install virtualenv
          
      - name: Cài kivy-ios
        script: |
          pip3 install kivy-ios
          
      - name: Build dependencies
        script: |
          cd $CM_BUILD_DIR
          mkdir -p iosbuild
          cd iosbuild
          
          # Build các thư viện chính
          toolchain build python3
          toolchain build kivy
          toolchain build pillow
          
          # Bỏ requests & pycryptodome (dùng UrlRequest + base64 là đủ)
          
      - name: Tạo project từ main.py
        script: |
          cd $CM_BUILD_DIR/iosbuild
          
          # Kiểm tra file main.py
          echo "Checking file main.py"
          ls -la ../
          
          # Tạo project
          toolchain create $APP_NAME ../main.py
          
      - name: Tạo Xcode project & sửa Bundle ID
        script: |
          cd $CM_BUILD_DIR/iosbuild
          toolchain xcode $APP_NAME
          cd $CM_BUILD_DIR/iosbuild/$APP_NAME-ios
          
          # Sửa CFBundleIdentifier
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" "$APP_NAME/Info.plist"
          
      - name: Build IPA unsigned
        script: |
          cd $CM_BUILD_DIR/iosbuild/$APP_NAME-ios
          xcodebuild -scheme $APP_NAME -configuration Release -archivePath $APP_NAME.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive -archivePath $APP_NAME.xcarchive -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?><plist version="1.0"><dict><key>method</key><string>development</string><key>signingStyle</key><string>manual</string></dict></plist>') -exportPath build/Release-iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          
    artifacts:
      - iosbuild/$APP_NAME-ios/build/Release-iphoneos/*.ipa
