name: Build iOS App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          brew update
          brew install autoconf automake libtool pkg-config gettext
          python -m pip install --upgrade pip
          python -m pip install Cython
          python -m pip install kivy-ios==1.3.0

      - name: Build Kivy iOS app
        run: |
          cd ${{ github.workspace }}
          mkdir -p iosbuild
          cd iosbuild
          
          # Tạo symlink cython-2.7
          CYTHON_PATH=$(which cython)
          sudo ln -sf "$CYTHON_PATH" /usr/local/bin/cython-2.7
          
          # Patch toolchain.py
          TOOLCHAIN_PATH=$(python -c "import kivy_ios; print(kivy_ios.__path__[0])")/toolchain.py
          python -c "
          import re
          with open('$TOOLCHAIN_PATH', 'r') as f:
              content = f.read()
          # Sửa cython variants
          content = re.sub(r'cython_variants\\s*=\\s*\\([^)]*\\)', 'cython_variants = (\"cython\", \"cython3\")', content)
          # Sửa compress program
          content = re.sub(r'--use-compress-program=[^\']*\\\\n', '--use-compress-program=gzip', content)
          with open('$TOOLCHAIN_PATH', 'w') as f:
              f.write(content)
          print('Patched toolchain.py successfully')
          "
          
          # Build tất cả
          python -m kivy_ios.toolchain build python3
          python -m kivy_ios.toolchain build kivy
          python -m kivy_ios.toolchain create beluga_chat_app ../main.py
          python -m kivy_ios.toolchain build beluga_chat_app
          python -m kivy_ios.toolchain xcode beluga_chat_app
          
          # Build IPA không ký
          cd beluga_chat_app-ios
          xcodebuild -scheme beluga_chat_app -configuration Release -archivePath beluga_chat_app.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: beluga-chat-ios
          path: ${{ github.workspace }}/iosbuild/beluga_chat_app-ios/build/Release-iphoneos/
