name: Build iOS App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          brew update
          brew install autoconf automake libtool pkg-config gettext ccache pigz
          python -m pip install --upgrade pip
          python -m pip install Cython
          python -m pip install kivy-ios==1.3.0

      - name: Fix kivy-ios toolchain
        run: |
          TOOLCHAIN_PATH=$(python -c "import kivy_ios; print(kivy_ios.__path__[0])")/toolchain.py
          echo "Patching $TOOLCHAIN_PATH"
          
          # Lưu bản backup
          cp "$TOOLCHAIN_PATH" "${TOOLCHAIN_PATH}.backup"
          
          # Tạo script sửa lỗi
          cat > fix_toolchain.py << 'EOF'
          import re
          import sys
          
          # Đọc file path từ argument
          toolchain_path = sys.argv[1]
          
          with open(toolchain_path, 'r') as f:
              content = f.read()
          
          # 1. Fix cython variants
          content = re.sub(r'cython_variants\s*=\s*\([^)]*\)', 'cython_variants = ("cython", "cython3")', content)
          
          # 2. Fix compress program format
          content = re.sub(r'comp\s*=\s*[\'"](--use-compress-program=[^\'"]*)[\'"]', r'comp = "\1"', content)
          
          # 3. Fix cho ccache, pigz, pbzip2 - thêm try-except
          content = re.sub(
              r'(\s+)self\.ccache = sh\.which\([\'"]ccache[\'"]\)',
              r'\1try:\n\1    self.ccache = sh.which("ccache")\n\1except:\n\1    print("ccache not found, disabling")\n\1    self.ccache = None',
              content
          )
          
          content = re.sub(
              r'(\s+)self\.use_pigz = sh\.which\([\'"]pigz[\'"]\)',
              r'\1try:\n\1    self.use_pigz = sh.which("pigz")\n\1except:\n\1    print("pigz not found, using standard gzip")\n\1    self.use_pigz = None',
              content
          )
          
          content = re.sub(
              r'(\s+)self\.use_pbzip2 = sh\.which\([\'"]pbzip2[\'"]\)',
              r'\1try:\n\1    self.use_pbzip2 = sh.which("pbzip2")\n\1except:\n\1    print("pbzip2 not found, using standard bzip2")\n\1    self.use_pbzip2 = None',
              content
          )
          
          # Lưu file đã sửa
          with open(toolchain_path, 'w') as f:
              f.write(content)
          
          print("Successfully patched toolchain.py")
          EOF
          
          # Chạy script
          python fix_toolchain.py "$TOOLCHAIN_PATH"
          
          # Tạo symlink cython-2.7
          CYTHON_PATH=$(which cython)
          sudo ln -sf "$CYTHON_PATH" /usr/local/bin/cython-2.7
          echo "Created cython-2.7 symlink pointing to $CYTHON_PATH"

      - name: Build Kivy iOS app
        run: |
          cd ${{ github.workspace }}
          mkdir -p iosbuild
          cd iosbuild
          
          # Build theo từng bước
          echo "Building hostpython3..."
          python -m kivy_ios.toolchain build hostpython3
          
          echo "Building kivy..."
          python -m kivy_ios.toolchain build kivy
          
          echo "Creating app..."
          python -m kivy_ios.toolchain create beluga_chat_app ../main.py
          
          echo "Building app..."
          python -m kivy_ios.toolchain build beluga_chat_app
          
          echo "Creating Xcode project..."
          python -m kivy_ios.toolchain xcode beluga_chat_app
          
          echo "Building IPA không ký..."
          cd beluga_chat_app-ios
          xcodebuild -scheme beluga_chat_app -configuration Release -archivePath beluga_chat_app.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: beluga-chat-ios
          path: ${{ github.workspace }}/iosbuild/beluga_chat_app-ios/build/Release-iphoneos/
