name: Build iOS App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          brew update
          brew install autoconf automake libtool pkg-config gettext ccache pigz
          python -m pip install --upgrade pip
          python -m pip install Cython
          python -m pip install kivy-ios==1.2.1  # Phiên bản cũ hơn, ổn định hơn

      - name: Fix kivy-ios toolchain
        run: |
          TOOLCHAIN_PATH=$(python -c "import kivy_ios; print(kivy_ios.__path__[0])")/toolchain.py
          echo "Patching $TOOLCHAIN_PATH"
          
          # Lưu bản backup
          cp "$TOOLCHAIN_PATH" "${TOOLCHAIN_PATH}.backup"
          
          # Patch trực tiếp bằng sed
          # 1. Fix cython variants
          sed -i '' -e 's/cython_variants\s*=\s*("cython-2.7", "cython", "cython3")/cython_variants = ("cython", "cython3")/g' "$TOOLCHAIN_PATH"
          
          # 2. Fix ccache, pigz, pbzip2
          sed -i '' -E 's/([ \t]+)self\.ccache = sh\.which\(["'\''](ccache)["'\'']\)/\1try:\n\1    self.ccache = sh.which("\2")\n\1except:\n\1    print("\2 not found, disabling")\n\1    self.ccache = None/g' "$TOOLCHAIN_PATH"
          
          sed -i '' -E 's/([ \t]+)self\.use_pigz = sh\.which\(["'\''](pigz)["'\'']\)/\1try:\n\1    self.use_pigz = sh.which("\2")\n\1except:\n\1    print("\2 not found, using standard gzip")\n\1    self.use_pigz = None/g' "$TOOLCHAIN_PATH"
          
          sed -i '' -E 's/([ \t]+)self\.use_pbzip2 = sh\.which\(["'\''](pbzip2)["'\'']\)/\1try:\n\1    self.use_pbzip2 = sh.which("\2")\n\1except:\n\1    print("\2 not found, using standard bzip2")\n\1    self.use_pbzip2 = None/g' "$TOOLCHAIN_PATH"
          
          # Sửa flags Xcode (xóa bitcode vì đã loại bỏ)
          sed -i '' -e 's/BITCODE_GENERATION_MODE=bitcode //g' "$TOOLCHAIN_PATH"
          
          # Tạo symlink cython-2.7
          CYTHON_PATH=$(which cython)
          sudo ln -sf "$CYTHON_PATH" /usr/local/bin/cython-2.7
          echo "Created cython-2.7 symlink pointing to $CYTHON_PATH"

      - name: Build Kivy iOS app
        run: |
          cd ${{ github.workspace }}
          mkdir -p iosbuild
          cd iosbuild
          
          # Tạo build script custom
          cat > build_app.sh << 'EOF'
          #!/bin/bash
          set -e  # Exit on first error
          
          # Build theo từng bước
          echo "===== Building hostpython3 ====="
          python -m kivy_ios.toolchain build hostpython3
          
          echo "===== Building libffi ====="
          # Thử fix libffi
          LIBFFI_PATH=$(python -c "import kivy_ios; import os; print(os.path.join(kivy_ios.__path__[0], 'recipes', 'libffi', '__init__.py'))")
          sed -i '' -e 's/BITCODE_GENERATION_MODE=bitcode //g' "$LIBFFI_PATH"
          python -m kivy_ios.toolchain build libffi
          
          echo "===== Building openssl ====="
          python -m kivy_ios.toolchain build openssl
          
          echo "===== Building kivy ====="
          python -m kivy_ios.toolchain build kivy
          
          echo "===== Creating app ====="
          python -m kivy_ios.toolchain create beluga_chat_app ../main.py || exit 1
          
          echo "===== Building app ====="
          cd beluga_chat_app-ios
          sed -i '' -e 's/BITCODE_GENERATION_MODE=bitcode //g' *.xcodeproj/project.pbxproj
          cd ..
          python -m kivy_ios.toolchain build beluga_chat_app
          
          echo "===== Creating Xcode project ====="
          python -m kivy_ios.toolchain xcode beluga_chat_app
          
          echo "===== Building IPA ====="
          cd beluga_chat_app-ios
          xcodebuild -scheme beluga_chat_app -configuration Release -archivePath beluga_chat_app.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          EOF
          
          chmod +x build_app.sh
          ./build_app.sh

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: beluga-chat-ios
          path: ${{ github.workspace }}/iosbuild/beluga_chat_app-ios/build/Release-iphoneos/
