name: Build iOS App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Clone kivy-ios directly
        run: |
          git clone https://github.com/kivy/kivy-ios.git
          cd kivy-ios
          python -m pip install -e .

      - name: Install dependencies
        run: |
          brew update
          brew install autoconf automake libtool pkg-config gettext
          python -m pip install --upgrade pip
          python -m pip install Cython

      - name: Full build attempt
        run: |
          cd ${{ github.workspace }}
          mkdir -p iosbuild
          cd iosbuild
          
          # Symlink cython
          CYTHON_PATH=$(which cython)
          sudo ln -sf "$CYTHON_PATH" /usr/local/bin/cython-2.7
          
          # Chạy toàn bộ quá trình build
          cd ${{ github.workspace }}/kivy-ios
          python toolchain.py build python3 || true
          python toolchain.py build kivy || true
          
          # Tạo và build ứng dụng
          echo "Creating app with improved error handling..."
          python toolchain.py create ${{ github.workspace }}/iosbuild/beluga_chat ${{ github.workspace }}/main.py || true
          
          # Nếu create thành công, tiến hành build ứng dụng
          if [ -d "${{ github.workspace }}/iosbuild/beluga_chat-ios" ]; then
            cd ${{ github.workspace }}/iosbuild/beluga_chat-ios
            echo "Building Xcode project..."
            
            # Cập nhật Info.plist
            plutil -replace CFBundleIdentifier -string "com.beluga.chat" beluga_chat/Info.plist || true
            
            # Build ứng dụng
            xcodebuild -scheme beluga_chat -sdk iphoneos -configuration Release clean archive -archivePath build/beluga_chat.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO || true
            
            # Tạo IPA từ archive
            mkdir -p build/Payload
            cp -R build/beluga_chat.xcarchive/Products/Applications/beluga_chat.app build/Payload/
            cd build
            zip -r beluga_chat.ipa Payload
            echo "IPA created at ${{ github.workspace }}/iosbuild/beluga_chat-ios/build/beluga_chat.ipa"
          else
            echo "App creation failed, cannot build IPA"
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: beluga-chat-ios
          path: |
            ${{ github.workspace }}/kivy-ios/dist
            ${{ github.workspace }}/iosbuild
