name: Build iOS App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          brew update
          brew install autoconf automake libtool pkg-config ccache pigz pbzip2
          python -m pip install --upgrade pip
          pip install cookiecutter cython pillow
          pip install kivy

      - name: Prepare app directory
        run: |
          mkdir -p iosbuild
          cd iosbuild
          
          # Kiểm tra cấu trúc thư mục
          cd ..
          ls -la
          find . -type f -name "main.py" | sort

      - name: Install kivy-ios
        run: |
          # Cài đặt kivy-ios từ git để có phiên bản mới nhất
          git clone https://github.com/kivy/kivy-ios.git
          cd kivy-ios
          pip install -e .
          cd ..

      - name: Debug info
        run: |
          pwd
          ls -la
          python --version
          which python
          which cython
          python -c "import kivy_ios; print(kivy_ios.__path__[0])"

      - name: Create app
        run: |
          # Đường dẫn tới main.py (từ kiểm tra trước đó, biết chắc chắn vị trí)
          export MAIN_PY="$GITHUB_WORKSPACE/kivy_chat_app/main.py"
          
          if [ ! -f "$MAIN_PY" ]; then
            echo "Không tìm thấy file main.py tại đường dẫn: $MAIN_PY"
            find "$GITHUB_WORKSPACE" -name "main.py"
            exit 1
          fi
          
          echo "Đường dẫn tới main.py: $MAIN_PY"
          
          # Tạo ứng dụng iOS - chuyển tới thư mục gốc của kivy-ios
          cd kivy-ios
          python toolchain.py create BelugaChat "$MAIN_PY"
          
          # Hiển thị cấu trúc thư mục sau khi tạo
          ls -la
          find . -name "*.xcodeproj" || echo "Không tìm thấy file xcodeproj"

      - name: Build IPA
        run: |
          cd kivy-ios
          # Tìm project Xcode đã tạo
          XCODEPROJ=$(find . -name "*.xcodeproj" | head -n 1)
          APP_DIR=$(dirname "$XCODEPROJ")
          APP_NAME=$(basename "$APP_DIR" -ios)
          
          if [ -z "$XCODEPROJ" ]; then
            echo "Không tìm thấy project Xcode!"
            ls -la
            exit 1
          fi
          
          echo "Tìm thấy project: $XCODEPROJ, tên app: $APP_NAME"
          cd "$APP_DIR"
          
          # Build ứng dụng không ký
          xcodebuild -project "$APP_NAME.xcodeproj" -scheme "$APP_NAME" -sdk iphoneos -configuration Release clean archive -archivePath build/"$APP_NAME".xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          
          # Tạo IPA
          mkdir -p build/IPA
          cp -r build/"$APP_NAME".xcarchive/Products/Applications/"$APP_NAME".app build/IPA/
          cd build/IPA
          zip -r "$APP_NAME".ipa "$APP_NAME".app
          
          # Hiển thị kết quả
          ls -la
          cd ../..
          find . -name "*.ipa"

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: BelugaChat-iOS
          path: kivy-ios/*-ios/build/IPA/*.ipa
          if-no-files-found: warn 
