name: Build iOS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          brew update
          brew install autoconf automake libtool pkg-config gettext gawk
          python -m pip install --upgrade pip
          python -m pip install kivy-ios==1.3.0 Cython
          # Tạo các symlink cần thiết
          ln -sf $(which cython) /usr/local/bin/cython-2.7 || true

      - name: Build Kivy iOS app
        run: |
          cd ${{ github.workspace }}
          # Tạo thư mục build
          mkdir -p iosbuild
          cd iosbuild
          export PYTHONPATH=$(pwd)
          export PATH="/usr/local/bin:$PATH"
          
          # Fix lỗi extract trong toolchain.py
          TOOLCHAIN_PATH=$(python -c "import kivy_ios; print(kivy_ios.__path__[0])")/toolchain.py
          EXTRACT_LINE=$(grep -n "comp = '--use-compress-program=" $TOOLCHAIN_PATH | cut -d':' -f1)
          if [ ! -z "$EXTRACT_LINE" ]; then
            sed -i.bak "${EXTRACT_LINE}s/--use-compress-program=\(.*\)/--use-compress-program=\1/" $TOOLCHAIN_PATH
          fi
          
          # Build các dependency chính
          python -m kivy_ios.toolchain build hostpython3
          python -m kivy_ios.toolchain build python3
          python -m kivy_ios.toolchain build kivy
          
          # Tạo project và build
          python -m kivy_ios.toolchain create beluga_chat_app ../kivy_chat_app/main.py
          python -m kivy_ios.toolchain build beluga_chat_app
          python -m kivy_ios.toolchain xcode beluga_chat_app
          
          # Điều chỉnh bundle ID
          plutil -replace CFBundleIdentifier -string "com.beluga.chat" beluga_chat_app-ios/beluga_chat_app/Info.plist
          
          # Build project
          cd beluga_chat_app-ios
          xcodebuild -scheme beluga_chat_app -configuration Release -archivePath beluga_chat_app.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: beluga-chat-ios
          path: ${{ github.workspace }}/iosbuild/beluga_chat_app-ios/build/Release-iphoneos/
