- name: Build Kivy iOS app
  run: |
    cd ${{ github.workspace }}
    mkdir -p iosbuild
    cd iosbuild
    
    # Tạo symlink cython-2.7
    CYTHON_PATH=$(which cython)
    sudo ln -sf "$CYTHON_PATH" /usr/local/bin/cython-2.7
    
    # Kiểm tra toolchain
    TOOLCHAIN_PATH=$(python -c "import kivy_ios; print(kivy_ios.__path__[0])")/toolchain.py
    echo "Toolchain path: $TOOLCHAIN_PATH"
    
    # Thử build hostpython3
    python -m kivy_ios.toolchain build hostpython3
