name: Build iOS App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Clone kivy-ios directly
        run: |
          git clone https://github.com/kivy/kivy-ios.git
          cd kivy-ios
          python -m pip install -e .
          ls -la
          echo "Directly cloned kivy-ios repository"

      - name: Install dependencies
        run: |
          brew update
          brew install autoconf automake libtool pkg-config gettext ccache
          python -m pip install --upgrade pip
          python -m pip install Cython
          
          # Tạo symlink cython-2.7
          CYTHON_PATH=$(which cython)
          sudo ln -sf "$CYTHON_PATH" /usr/local/bin/cython-2.7

      - name: Check file structure
        run: |
          cd kivy-ios
          ls -la
          find . -name "toolchain.py"
          python toolchain.py --help || true
          
          # Xem workflows hỗ trợ
          echo "Available recipes:"
          python toolchain.py recipes || true

      - name: Build step-by-step
        run: |
          mkdir -p ${{ github.workspace }}/iosbuild
          cd ${{ github.workspace }}/iosbuild
          
          echo "====== Building python3 ======"
          cd ${{ github.workspace }}/kivy-ios
          python toolchain.py build python3 || true
          
          echo "====== Building kivy ======"
          python toolchain.py build kivy || true
          
          echo "====== Creating app ======"
          python toolchain.py create ${{ github.workspace }}/iosbuild/beluga_chat ../main.py || true
          
          echo "====== Looking for output files ======"
          cd ${{ github.workspace }}
          find . -name "*.app" -o -name "*.ipa" || true
          find kivy-ios -name "*.a" || true

      - name: Upload all build products
        uses: actions/upload-artifact@v4
        with:
          name: kivy-ios-build-outputs
          path: |
            ${{ github.workspace }}/kivy-ios/dist
            ${{ github.workspace }}/iosbuild
