name: Build iOS App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          brew update
          brew install autoconf automake libtool pkg-config gettext ccache pigz pbzip2
          python -m pip install --upgrade pip
          python -m pip install Cython pillow kivy

      - name: Clone kivy-ios directly
        run: |
          git clone https://github.com/kivy/kivy-ios.git
          cd kivy-ios
          python -m pip install -e .
          
          # Tạo symlink cython-2.7
          CYTHON_PATH=$(which cython)
          sudo ln -sf "$CYTHON_PATH" /usr/local/bin/cython-2.7
          
          echo "Available recipes:"
          python toolchain.py recipes || true

      - name: Build components
        run: |
          # Tìm main.py
          MAIN_PY="$GITHUB_WORKSPACE/main.py"
          if [ ! -f "$MAIN_PY" ]; then
            MAIN_PY=$(find $GITHUB_WORKSPACE -name "main.py" | grep -v "kivy-ios/tests" | head -n 1)
            if [ -z "$MAIN_PY" ]; then
              echo "❌ Không tìm thấy main.py!"
              exit 1
            fi
          fi
          echo "✅ Sử dụng main.py: $MAIN_PY"
          
          # Build từng bước
          cd kivy-ios
          export APP_NAME="beluga_chat"
          
          echo "====== Building python3 ======"
          python toolchain.py build python3 || true
          
          echo "====== Building kivy ======"
          python toolchain.py build kivy || true
          
          echo "====== Creating app ======"
          python toolchain.py create "$APP_NAME" "$MAIN_PY" || true
          
          # Kiểm tra kết quả
          if [ ! -d "$APP_NAME-ios" ]; then
            echo "❌ Không tạo được thư mục app!"
            exit 1
          fi

      - name: Package IPA
        run: |
          cd kivy-ios
          export APP_NAME="beluga_chat"
          cd "$APP_NAME-ios"
          
          # Chuẩn bị Info.plist
          if [ -f "$APP_NAME/Info.plist" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier com.beluga.chat" "$APP_NAME/Info.plist"
          fi
          
          # Build ứng dụng không ký
          xcodebuild -project "$APP_NAME.xcodeproj" -scheme "$APP_NAME" -sdk iphoneos -configuration Release clean archive -archivePath build/"$APP_NAME".xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO || true
          
          # Tạo IPA
          mkdir -p build/IPA
          if [ -d "build/$APP_NAME.xcarchive/Products/Applications/$APP_NAME.app" ]; then
            cp -r "build/$APP_NAME.xcarchive/Products/Applications/$APP_NAME.app" build/IPA/
            cd build/IPA
            zip -r "$APP_NAME.ipa" "$APP_NAME.app"
            echo "✅ Đã tạo IPA thành công"
          else
            echo "⚠️ Không tìm thấy .app, tạo IPA giả lập"
            cd ../..  # Quay lại $APP_NAME-ios
            
            # Tạo IPA thủ công từ thư mục dự án
            mkdir -p Payload
            if [ -d "$APP_NAME" ]; then
              cp -r "$APP_NAME" Payload/
              zip -r build/IPA/"$APP_NAME.ipa" Payload
              echo "✅ Đã tạo IPA thủ công từ thư mục dự án"
            else
              echo "❌ Không tìm thấy thư mục app để đóng gói"
              ls -la
              exit 1
            fi
          fi

      - name: Create Complete Package
        run: |
          # Tạo một gói hoàn chỉnh chứa cả dist và IPA
          mkdir -p complete_package
          
          # Sao chép thư mục dist
          cp -r kivy-ios/dist complete_package/
          
          # Sao chép thư mục project-ios
          cp -r kivy-ios/beluga_chat-ios complete_package/
          
          # Sao chép IPA nếu có
          cp -r kivy-ios/beluga_chat-ios/build/IPA complete_package/ || true
          
          # Nén thành một file duy nhất
          cd complete_package
          zip -r ../beluga_chat_complete.zip .
          cd ..
          
          echo "✅ Đã tạo gói hoàn chỉnh"
          find . -name "*.ipa" || echo "Không tìm thấy IPA"
          find . -name "*.zip" || echo "Không tìm thấy ZIP"

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: beluga-chat-ipa
          path: kivy-ios/beluga_chat-ios/build/IPA/*.ipa
          if-no-files-found: warn

      - name: Upload Complete Package
        uses: actions/upload-artifact@v4
        with:
          name: beluga-chat-complete
          path: beluga_chat_complete.zip
          if-no-files-found: warn
          
      - name: Upload Individual Components
        uses: actions/upload-artifact@v4
        with:
          name: kivy-ios-components
          path: |
            kivy-ios/dist
            kivy-ios/beluga_chat-ios
          if-no-files-found: warn 
